### ISSUE TITLE
questions + related packages

### ISSUE THREAD

**Issue by timotheecour** [PMunch/protobuf-nim#1]
* Are there examples demonstrating how to use your library?
* Could the design be inspired from https://github.com/msoucy/dproto ? that library allows creating proto definitions at compile time (and doing everything at compile time making use of reflection).
* would be nice having a section comparing against alternatives eg:

## related nim packages
* https://github.com/ivankoster/protobuf-nim
* https://github.com/huodon/protobuf
* https://github.com/oswjk/protobuf-nim + https://forum.nim-lang.org/t/3687
/cc @PMunch just added this one

**Comment by PMunch** [comment]
Currently this is a work in progress, and therefore doesn't have any examples yet.
Haven't seen dproto before, but looking at the example on their landing page this will work very similarly.

This implementation will read and parse the protobuf file (or string) on compile-time and generate the required types and read/write procs to parse data and to create and write data. So you will be able to load in a protobuf definition on compile-time, and then just declare an object of the defined type, set it's fields, and call `stream.write` on it to write it out. Or you could call the corresponding `stream.read<name of message>` on a read-stream and get out a message type.

ivankoster/protobuf-nim uses protoc (the "official" protobuf compiler that creates code in various languages), and huodon/protobuf seems to wrap the libprotobuf-c C library which means having to generate the C code and then running it through c2nim to get useable Nim code.

As I mentioned this is still a work in progress, however I hope to have some working examples over easter.

**Comment by PMunch** [comment]
As of the latest commit this is now able to actually read and write protobuf messages. If you are interested in seeing how this is going to work once everything is done you can have a look here: https://github.com/PMunch/protobuf-nim/blob/master/protobuf.nim#L1047-L1076 NOTE: The code that actually calls the protobuf generator is at line 1037.

This is still very early and rudimentary, and I don't expect everything to work. But if you want to try it out be my guest (and report any issues that you  find 😃). If you get an error about max iterations you are using a compiler that is too old, upgrade to the latest devel compiler and it should work fine (the parser creates some pretty deep call stacks).

**Comment by timotheecour** [comment]
thanks! blocked by https://github.com/PMunch/protobuf-nim/issues/3

**Comment by PMunch** [comment]
Added actual documentation now! I'll probably fix up combparser tomorrow and publish both on Nimble for easier install.
