### ISSUE TITLE
consider publishing as nimble package

### ISSUE THREAD

**Issue by timotheecour** [PMunch/protobuf-nim#2]
even if not complete yet; making it more searchable will make it less likely to have duplicate work
not to mention ease of use
- [x] create protobuf.nimble

- [x] publish (nimble publish?)
`nimble search proto|grep PMunch`
right now empty

- [ ] make protobuf.nimble aware of tests
for tests, maybe smthg like https://github.com/nim-lang/c2nim/blob/master/c2nim.nimble#L11 ?

- [ ] make protobuf.nimble aware of examples
not sure how to do that

- [x] make sure https://github.com/oswjk/protobuf-nim and https://github.com/PMunch/protobuf-nim use different names (nimble file + even repo name)

/cc @PMunch edited above

**Comment by PMunch** [comment]
Good point. I'm planning on adding some more tests and documentation today, so that would make it a bit more complete and I'll make a package for it.

**Comment by timotheecour** [comment]
* also consider adding github [topics](https://github.com/topics) to make it searcheable (as https://github.com/oswjk/protobuf-nim)

**Comment by PMunch** [comment]
Huh, never considered topics before. I'll make sure to add them!

**Comment by timotheecour** [comment]
@PMunch @oswjk 
both https://github.com/PMunch/protobuf-nim and https://github.com/oswjk/protobuf-nim define `protobuf.nimble` and this prevents both of these to be published to nimble.
Furthermore, having both repos named `protobuf-nim` is problematic, for eg, I forked both and it generates:
https://github.com/timotheecour/protobuf-nim and https://github.com/timotheecour/protobuf-nim-1 (impossible to tell where they came from unless one reads the metadata forked from X)

I think one of these repos + nimble file should be renamed (and the earlier the better to minimize pain for users of these)
name doesn't matter much so long they're different but here are some options:

* option 1:
renaming https://github.com/oswjk/protobuf-nim to https://github.com/oswjk/protobuf-protoc-nim
* option 2:
renaming https://github.com/PMunch/protobuf-nim to https://github.com/PMunch/protobuf-ct-nim

**Comment by PMunch** [comment]
We already had this, or a very similar, discussion over in https://github.com/nim-lang/packages/pull/694.

**Comment by PMunch** [comment]
I'll close this now, `protobuf` has been on Nimble for quite a while now :P Open separate issues if the two points left still aren't completed.
