### ISSUE TITLE
Error on empty protobuf definitions

### ISSUE THREAD

**Issue by BurnySc2** [PMunch/protobuf-nim#34]
With the current version that is installed via `nimble install protobuf`, the following protobuf code gets converted

```proto
syntax = "proto3";

message Request {}
```

```nim
import protobuf, streams

parseProtoFile("my_file.proto")
# nim c -d:echoProtobuf main.nim > types.nim
```

to

```nim
# Output from the nimble version 
{.experimental.}
type
  Request = ref object
    fields: set[range[0 .. -1]]
```
which results in the error: `Error: range is empty`

However, the current version in this repository does correctly convert empty definitions:

```nim
# Output if using the protobuf.nim file locally
{.experimental.}
type
  Request = ref object
```

Installing via `nimble install https://github.com/PMunch/protobuf-nim` did not help either, somehow. Only downloading the `protobuf.nim` directly and inserting it into my project helped.
Perhaps a version bump is required?

**Comment by PMunch** [comment]
Does indeed sound like a version bump issue. I'll fix it up tomorrow. In the meantime I believe `nimble install protobuf@HEAD` or similar will install the latest version

**Comment by PMunch** [comment]
Just bumped the version (sorry it took so long), could you try if it works now with the 0.5.3 version?
