### ISSUE TITLE
[BUG] Incorrect protobuf generation

### ISSUE THREAD

**Issue by ChanderG** [PMunch/protobuf-nim#35]
Not sure if this is related to #24, but here is a simpler example than the one shown there:
```
import protobuf, streams

proc echoDataStream1(stream: Stream) =
  stream.setPosition(0)
  while not stream.atEnd:
    let num = stream.readUint8()
    stdout.write num.toHex()
  stream.setPosition(0)

const testSpec = """
syntax = "proto3";

message Message {
  string name  = 1;
  string value = 2;
}

message NestedMessage {
  repeated Message content = 1;
}

message DoubleNestedMessage {
  NestedMessage body = 1;
}
"""
parseProto(testSpec)

var msg1 = new Message
msg1.name = "Hello"
msg1.value = "World"
var msg2 = new Message
msg2.name = "Foo"
msg2.value = "Bar"

var nmsg = new NestedMessage
nmsg.content = @[msg1, msg2]

var dnmsg = new DoubleNestedMessage
dnmsg.body = nmsg

var ds = newStringStream()
ds.write dnmsg
ds.setPosition 0

ds.echoDataStream1
```

The output is of this program is:
```
0a1b0a0e0a0548656c6c6f1205576f726c640a0a0a03466f6f1203426172
```
while it should be:
```
0a1c0a0e0a0548656c6c6f1205576f726c640a0a0a03466f6f1203426172
```
the only difference being in the 4th position: "b" instead of "c".
(This verification done using protoscope).

Fwiw, the following scenarios work correctly:
1. Using only 1 layer of nesting, so no "DoubleNestedMessage".
2. Using 2 layers of nesting, but no "repeated" in the inner layer.

**Comment by PMunch** [comment]
Should be fixed now as of 0.5.4, also added your minimal sample as a test-case. Thanks for the issue, and sorry it took so long to get it fixed (especially looking at how easy the fix turned out to be).
